services:
  db:
    image: postgres:16-alpine
    container_name: links-resource-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: links_resource
    ports:
      - "5433:5432"
    volumes:
      - links_resource_pgdata:/var/lib/postgresql/data

volumes:
  links_resource_pgdata:
